# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
