# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0004_secrets_like_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secrets',
            name='like_id',
        ),
    ]
