# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0005_remove_secrets_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
