# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0007_auto_20170530_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
    ]
